
import React from "react";
import { StarIcon, GiftIcon, GiftCheckIcon, HumanIcon, BackIcon, BuddyAvatar, BlueAvatar } from "../icons";

export const starData = [
    {
        id: "m5gr84i9",
        status: "reward",
        name: 'string',
        product: 'string',
        issue_date: '2023/02/02',
        expiry_date: '2023/02/02',
        size: 'string',
    },
    {
        id: "m5gr84i9",
        status: "reward",
        name: 'string',
        product: 'string',
        issue_date: '2023/02/02',
        expiry_date: '2023/02/02',
        size: 'string',
    },
    {
        id: "m5gr84i9",
        status: "reward",
        name: 'string',
        product: 'string',
        issue_date: '2023/02/02',
        expiry_date: '2023/02/02',
        size: 'string',
    },
    {
        id: "m5gr84i9",
        status: "reward",
        name: 'string',
        product: 'string',
        issue_date: '2023/02/02',
        expiry_date: '2023/02/02',
        size: 'string',
    },
    {
        id: "m5gr84i9",
        status: "current",
        name: 'string',
        product: 'string',
        issue_date: '2023/02/02',
        expiry_date: '2023/02/02',
        size: 'string',
    },
    {
        id: "m5gr84i9",
        status: "reward",
        name: 'string',
        product: 'string',
        issue_date: '2023/02/02',
        expiry_date: '2023/02/02',
        size: 'string',
    },
    {
        id: "m5gr84i9",
        status: "expiring",
        name: 'string',
        product: 'string',
        issue_date: '2023/02/02',
        expiry_date: '2023/02/02',
        size: 'string',
    },
    {
        id: "m5gr84i9",
        status: "reward",
        name: 'string',
        product: 'string',
        issue_date: '2023/02/02',
        expiry_date: '2023/02/02',
        size: 'string',
    },
    {
        id: "m5gr84i9",
        status: "reward",
        name: 'string',
        product: 'string',
        issue_date: '2023/02/02',
        expiry_date: '2023/02/02',
        size: 'string',
    },
    {
        id: "m5gr84i9",
        status: "expired",
        name: 'string',
        product: 'string',
        issue_date: '2023/02/02',
        expiry_date: '2023/02/02',
        size: 'string',
    },
    {
        id: "m5gr84i9",
        status: "expired",
        name: 'string',
        product: 'string',
        issue_date: '2023/02/02',
        expiry_date: '2023/02/02',
        size: 'string',
    },
];

export const rewardData = [
    {
        id: "m5gr84i9",
        status: "issued",
        first_name: 'string',
        last_name: 'string',
        pet_name: 'string',
        issue_date: '2023/02/02',
        redeemed_date: '2023/02/02',
        expiry_date: '2023/02/02',
        size: 'string',
    },
    {
        id: "m5gr84i9",
        status: "issued",
        first_name: 'string',
        last_name: 'string',
        pet_name: 'string',
        issue_date: '2023/02/02',
        redeemed_date: '2023/02/02',
        expiry_date: '2023/02/02',
        size: 'string',
    },
    {
        id: "m5gr84i9",
        status: "issued",
        first_name: 'string',
        last_name: 'string',
        pet_name: 'string',
        issue_date: '2023/02/02',
        redeemed_date: '2023/02/02',
        expiry_date: '2023/02/02',
        size: 'string',
    },
    {
        id: "m5gr84i9",
        status: "issued",
        first_name: 'string',
        last_name: 'string',
        pet_name: 'string',
        issue_date: '2023/02/02',
        redeemed_date: '2023/02/02',
        expiry_date: '2023/02/02',
        size: 'string',
    },
    {
        id: "m5gr84i9",
        status: "redeemed",
        first_name: 'string',
        last_name: 'string',
        pet_name: 'string',
        issue_date: '2023/02/02',
        redeemed_date: '2023/02/02',
        expiry_date: '2023/02/02',
        size: 'string',
    },
    {
        id: "m5gr84i9",
        status: "issued",
        first_name: 'string',
        last_name: 'string',
        pet_name: 'string',
        issue_date: '2023/02/02',
        redeemed_date: '2023/02/02',
        expiry_date: '2023/02/02',
        size: 'string',
    },
    {
        id: "m5gr84i9",
        status: "reconciled",
        first_name: 'string',
        last_name: 'string',
        pet_name: 'string',
        issue_date: '2023/02/02',
        redeemed_date: '2023/02/02',
        expiry_date: '2023/02/02',
        size: 'string',
    },
    {
        id: "m5gr84i9",
        status: "issued",
        first_name: 'string',
        last_name: 'string',
        pet_name: 'string',
        issue_date: '2023/02/02',
        redeemed_date: '2023/02/02',
        expiry_date: '2023/02/02',
        size: 'string',
    },
    {
        id: "m5gr84i9",
        status: "issued",
        first_name: 'string',
        last_name: 'string',
        pet_name: 'string',
        issue_date: '2023/02/02',
        redeemed_date: '2023/02/02',
        expiry_date: '2023/02/02',
        size: 'string',
    },
    {
        id: "m5gr84i9",
        status: "expired",
        first_name: 'string',
        last_name: 'string',
        pet_name: 'string',
        issue_date: '2023/02/02',
        redeemed_date: '2023/02/02',
        expiry_date: '2023/02/02',
        size: 'string',
    },
    {
        id: "m5gr84i9",
        status: "expired",
        first_name: 'string',
        last_name: 'string',
        pet_name: 'string',
        issue_date: '2023/02/02',
        redeemed_date: '2023/02/02',
        expiry_date: '2023/02/02',
        size: 'string',
    },
];

export const dashboardCards = [
    { number: 344, title: "Pet owner joins", color: "primary", icon: React.createElement(HumanIcon, { className: "w-3 h-3" }) },
    { number: 1208, title: "Stars earned", color: "success", icon: React.createElement(StarIcon, { className: "w-3 h-3" }) },
    { number: 210, title: "Rewards issued", color: "success", icon: React.createElement(GiftIcon, { className: "w-3 h-3" }) },
    { number: 61, title: "Rewards redeemed", color: "info", icon: React.createElement(GiftCheckIcon, { className: "w-3 h-3" }) },
];

export const dashboardSelectOptions = ["All times", "Option 1", "Option 2", "Option 3"];

export const dashboardTabOptions = ["Pet owner joins", "Stars", "Rewards"];

export const starCards = [
    { number: 13, title: "Total stars", color: "primary", icon: React.createElement(StarIcon, { className: "w-3 h-3" }) },
    { number: 0, title: "Current stars", color: "success", icon: React.createElement(StarIcon, { className: "w-3 h-3" }) },
    { number: 1, title: "Stars expired", color: "error", icon: React.createElement(StarIcon, { className: "w-3 h-3" }) },
];

export const petCards = [
    {
        petName: "Blue",
        petIcon: React.createElement(BlueAvatar, { className: "w-10 h-10" }),
        weight: "Medium dog(10-20kg)",
        gender: "Male",
        birthDate: "10/10/2022 - 3 years old",
        totalStars: 8,
        totalRedeemed: 1,
        treatmentPeriod: "5 days",
        color: "#EF4166",
    },
    {
        petName: "Buddy",
        petIcon: React.createElement(BuddyAvatar, { className: "w-10 h-10" }),
        weight: "Medium dog(10-20kg)",
        gender: "Male",
        birthDate: "01/01/2024 - 1 years old",
        totalStars: 1,
        totalRedeemed: 4,
        treatmentPeriod: "2 weeks",
        color: "#0096D7",
    },
];

export const petTabOptions = ["Stars", "Rewards"];

export const petSelectOptions = ["All pets", "Option 1", "Option 2", "Option 3"];